let products=[],cart=[],activeCat="";
async function load(){try{products=await (await fetch("https://theroyalfashion.onrender.com/api/products")).json();renderProducts()}catch(e){document.querySelector("#grid").innerHTML='<div class="loading">Unable to load products.</div>'}}
function filterCat(c){activeCat=c;document.querySelector("#products").scrollIntoView({behavior:"smooth"});renderProducts()}
function renderProducts(){const q=(document.querySelector("#search")?.value||"").toLowerCase();let list=products.filter(p=>(!activeCat||p.category===activeCat)&&(`${p.name} ${p.category}`.toLowerCase().includes(q)));const g=document.querySelector("#grid");if(!list.length){g.innerHTML='<div class="loading">No products found. Add products from your admin panel.</div>';return}g.innerHTML=list.map(p=>`<article class="card"><div class="pic">${p.image?`<img src="${p.image}" alt="${esc(p.name)}">`:'<span class="placeholder">♛</span>'}</div><div class="info"><div class="cat">${esc(p.category)}</div><div class="name">${esc(p.name)}</div><div class="price">${p.comparePrice?`<span class="old">₹${p.comparePrice}</span>`:""}₹${p.price}</div><button class="add" onclick="add(${JSON.stringify(p.id)})">ADD TO BAG</button></div></article>`).join("")}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({...p,qty:1});renderCart();openCart()}
function renderCart(){document.querySelector("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0);document.querySelector("#cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><div class="thumb">${x.image?`<img src="${x.image}" style="width:100%;height:100%;object-fit:cover">`:"♛"}</div><div><b>${esc(x.name)}</b><div>₹${x.price} × ${x.qty}</div></div></div>`).join(""):'<p style="color:#888">Your bag is empty.</p>';document.querySelector("#cartTotal").textContent="₹"+cart.reduce((a,x)=>a+x.price*x.qty,0)}
function openCart(){document.querySelector("#cart").classList.add("open");document.querySelector("#shade").classList.add("open")}
function closeCart(){document.querySelector("#cart").classList.remove("open");document.querySelector("#shade").classList.remove("open")}
function checkout(){if(!cart.length)return alert("Your bag is empty.");const customer=prompt("Customer name:");if(!customer)return;const phone=prompt("Mobile number:");if(!phone)return;const address=prompt("Full delivery address:");if(!address)return;const total=cart.reduce((a,x)=>a+x.price*x.qty,0);fetch(fetch("https://theroyalfashion.onrender.com/api/orders",{,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer,phone,address,items:cart.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty})),total})}).then(r=>r.json()).then(d=>{if(d.ok){alert("Order placed successfully! Order ID: "+d.orderId);cart=[];renderCart();closeCart()}else alert(d.error||"Order failed.")})}
load();